typography_spectrum: 0.45382773340679705
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.6383362107444555
  lightness: 0.3262106846086681
  saturation: 0.6047658668830991
  rhythmicContrast: 0.7608615264762193
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10144167277030647
analytics:
  google: null
  facebook: null
  twitter: null
name: Intreccio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Visit our Shop
    url: 'https://www.etsy.com/shop/Intreccio?ref=hdr_shop_menu'
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Intreccio Giant Knitting
purpose: []
