typography_spectrum: 0.4978724
color:
  brandColors:
    - '#FFFFFF'
    - '#95D6FE'
    - '#575A61'
    - '#6A9CCD'
    - '#0F1628'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.91633
analytics:
  google: null
  facebook: null
  twitter: null
name: Intreccio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Visit our Shop
    url: 'https://www.etsy.com/shop/Intreccio?ref=hdr_shop_menu'
    type: external
  - name: Blog
    id: beede1eb-853c-4ef8-b47e-282c1087512c
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Intreccio Giant Knitting
purpose: []
