name: Intreccio
favicon: null
layout_spectrum: 0.24874
typography_spectrum: 0.8112099720165133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#95D6FE'
    - '#575A61'
    - '#6A9CCD'
    - '#0F1628'
  brandStrength: 0.875
  lightness: 0.32239482132717967
  saturation: 0.6763669073116034
  rhythmicContrast: 0.8790286695584655
purpose: []
