name: Intreccio
favicon: null
layout_spectrum: 0.24874
typography_spectrum: 0.12538
title: Intreccio Giant Knitting
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100c0b'
    - '#4f595b'
    - '#f696bc'
    - '#fffee0'
    - '#d78f29'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.2425532
purpose: []
