name: Intreccio
favicon: null
layout_spectrum: 0.75632
typography_spectrum: 0.76672
title: Intreccio Giant Knitting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9dbbe'
    - '#0b0f0e'
    - '#406150'
    - '#8f9186'
    - '#fff05c'
  brandStrength: 0.5
  lightness: 0.32239482132717967
  saturation: 0.6763669073116034
  rhythmicContrast: 0.5
purpose: []
